easy_config.type.*:
  type: config_entity
  label: 'Easy config type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    module:
      type: string
      label: 'Module'
    description:
      type: text
      label: 'Description'
    uuid:
      type: string
